# Generated by Django 4.1.2 on 2023-03-07 10:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('category_image', models.ImageField(blank=True, upload_to='newfile/')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('publish', models.BooleanField(default=True)),
                ('has_session', models.BooleanField(default=False)),
                ('is_sub', models.BooleanField(default=False)),
                ('dateCreate', models.DateTimeField(default=django.utils.timezone.now)),
                ('dateUpdate', models.DateTimeField(auto_now=True)),
                ('parent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_sub', to='nestedapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('publish', models.BooleanField(default=True)),
                ('createDate', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nestedapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(max_length=100)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('masenger', models.CharField(blank=True, max_length=100)),
                ('courseIcon', models.ImageField(blank=True, upload_to='courseIcon/')),
                ('courseBanner', models.ImageField(blank=True, upload_to='courseBanner/')),
                ('publish', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='nestedapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Depertment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depName', models.CharField(max_length=100)),
                ('shortName', models.CharField(blank=True, max_length=100)),
                ('dep_icon', models.ImageField(blank=True, upload_to='icon/')),
                ('dep_thumbnail', models.ImageField(blank=True, upload_to='thumbnail/')),
                ('publish', models.BooleanField(default=True)),
                ('depMakeDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nestedapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nestedapp.category')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nestedapp.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Physics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('add_to_api', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(null=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('course', models.ManyToManyField(to='nestedapp.coursemodel')),
            ],
        ),
        migrations.CreateModel(
            name='SessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('publish', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.CharField(max_length=500)),
                ('publish', models.BooleanField(default=True)),
                ('view', models.BooleanField(default=False)),
                ('stream', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(blank=True, upload_to='vid_thumb/')),
                ('video', models.FileField(blank=True, upload_to='videos/')),
                ('creatDate', models.DateField(auto_now_add=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='videoTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic', models.BooleanField(default=False)),
                ('premium', models.BooleanField(default=False)),
                ('diamond', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='nestedapp.package')),
                ('videos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='nestedapp.video')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subCode', models.IntegerField(null=True)),
                ('order', models.IntegerField(null=True)),
                ('subImage', models.ImageField(blank=True, upload_to='subImage/')),
                ('publish', models.BooleanField(default=True)),
                ('primaryColor', models.CharField(blank=True, max_length=50)),
                ('secondaryColor', models.CharField(blank=True, max_length=50)),
                ('createDate', models.DateField(default=datetime.datetime.now)),
                ('updatedDate', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nestedapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='SessionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_semester', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_category', to='nestedapp.category')),
                ('semester', models.ManyToManyField(to='nestedapp.semester')),
                ('session', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='session', to='nestedapp.sessionmodel')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nestedapp.subject'),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, upload_to='instructor_pic/')),
                ('available', models.BooleanField(default=True)),
                ('creating_date', models.DateField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inst_department', to='nestedapp.depertment')),
            ],
        ),
       
        migrations.AddField(
            model_name='coursemodel',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='nestedapp.depertment'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='nestedapp.instructor'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='nestedapp.instructor'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='prerequisites',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nestedapp.coursemodel'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='subject',
            field=models.ManyToManyField(related_name='subject', to='nestedapp.subject'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nestedapp.subject'),
        ),
    ]
