# Generated by Django 4.1.2 on 2023-03-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nestedapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='endCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('days', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ManyToManyField(to='nestedapp.coursemodel')),
            ],
        ),
    ]
