# Generated by Django 4.1.2 on 2023-03-23 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nestedapp', '0002_endcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='coursePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('B', 'Basic'), ('P', 'Premium'), ('D', 'Diamond')], max_length=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nestedapp.coursemodel')),
            ],
        ),
    ]
