# Generated by Django 4.1.2 on 2023-03-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nestedapp', '0003_courseplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseplan',
            name='course',
        ),
        migrations.AddField(
            model_name='courseplan',
            name='course_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseplan',
            name='course_hour',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='courseplan',
            name='course_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='courseplan',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='courseplan',
            name='total_notebook',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseplan',
            name='total_quiz',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
