# Generated by Django 4.1.2 on 2023-03-23 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nestedapp', '0004_remove_courseplan_course_courseplan_course_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videos', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nestedapp.coursemodel')),
                ('plan', models.ManyToManyField(to='nestedapp.courseplan')),
            ],
        ),
    ]
