# Generated by Django 4.1.2 on 2023-04-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nestedapp', '0005_coursedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='plan',
            field=models.ManyToManyField(blank=True, to='nestedapp.courseplan'),
        ),
        migrations.AlterField(
            model_name='courseplan',
            name='plan',
            field=models.CharField(max_length=50),
        ),
    ]
