# Generated by Django 4.1.2 on 2023-04-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nestedapp', '0006_alter_coursedetails_plan_alter_courseplan_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseplan',
            name='course_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courseplan',
            name='course_hour',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courseplan',
            name='total_notebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courseplan',
            name='total_quiz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
