# Generated by Django 4.1.2 on 2022-11-09 12:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nestedapp', '0008_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subCode', models.IntegerField(null=True)),
                ('order', models.IntegerField(null=True)),
                ('subImage', models.ImageField(blank=True, upload_to='subImage/')),
                ('publish', models.BooleanField(default=True)),
                ('primaryColor', models.CharField(blank=True, max_length=50)),
                ('secondaryColor', models.CharField(blank=True, max_length=50)),
                ('createDate', models.DateField(default=datetime.datetime.now)),
                ('updatedDate', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nestedapp.category')),
            ],
        ),
    ]
