# Generated by Django 4.1.2 on 2023-02-18 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nestedapp', '0015_alter_category_parent_alter_semester_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField(max_length=50)),
                ('publish', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='semester',
            name='category',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='department',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='name',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='publish',
        ),
        migrations.AddField(
            model_name='category',
            name='has_session',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='is_sub',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='semester',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='semester',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='startDate',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='SessionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_semester', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_category', to='nestedapp.category')),
                ('semester', models.ManyToManyField(to='nestedapp.semester')),
                ('session', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='session', to='nestedapp.sessionmodel')),
            ],
        ),
    ]
