# Generated by Django 4.1.2 on 2023-01-16 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nestedapp', '0015_alter_category_parent_alter_semester_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='order',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='nestedapp.subject'),
        ),
    ]
