# Generated by Django 4.1.2 on 2023-01-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nestedapp', '0016_alter_coursemodel_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='subject',
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='subject',
            field=models.ManyToManyField(to='nestedapp.subject'),
        ),
    ]
