# Generated by Django 4.1.2 on 2023-02-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nestedapp', '0016_sessionmodel_remove_semester_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessioncategory',
            name='semester',
            field=models.ManyToManyField(blank=True, to='nestedapp.semester'),
        ),
    ]
