# Generated by Django 4.1.2 on 2023-02-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nestedapp', '0017_alter_sessioncategory_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='course',
            field=models.ManyToManyField(to='nestedapp.coursemodel'),
        ),
        migrations.AlterField(
            model_name='sessioncategory',
            name='semester',
            field=models.ManyToManyField(to='nestedapp.semester'),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='year',
            field=models.IntegerField(),
        ),
    ]
