# Generated by Django 4.1.2 on 2023-01-31 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nestedapp', '0020_instructor_creating_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('publish', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='nestedapp.category'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='nestedapp.depertment'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='subject',
            field=models.ManyToManyField(related_name='subject', to='nestedapp.subject'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inst_department', to='nestedapp.depertment'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sem_department', to='nestedapp.depertment'),
        ),
    ]
