# Generated by Django 4.1.2 on 2023-02-04 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nestedapp', '0024_alter_sessionmodel_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_semester', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_category', to='nestedapp.category')),
                ('session', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='session', to='nestedapp.sessionmodel')),
            ],
        ),
    ]
