# Generated by Django 4.1.2 on 2023-02-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nestedapp', '0028_alter_semester_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='course',
            field=models.ManyToManyField(to='nestedapp.coursemodel'),
        ),
    ]
