# Generated by Django 4.1.2 on 2022-11-03 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Physics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('add_to_api', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('category_image', models.ImageField(blank=True, upload_to='upload/')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('publish', models.BooleanField(default=True)),
                ('parent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nestedapp.category')),
            ],
        ),
    ]
