# Generated by Django 4.1.2 on 2022-11-03 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nestedapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='dateCreate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='dateUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
