# Generated by Django 4.1.2 on 2022-11-03 11:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nestedapp', '0002_category_datecreate_category_dateupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='dateCreate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='category',
            name='dateUpdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
