# Generated by Django 4.1.2 on 2022-11-06 06:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nestedapp', '0003_alter_category_datecreate_alter_category_dateupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, upload_to='newfile/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='dateUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Depertment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depName', models.CharField(max_length=100)),
                ('shortName', models.CharField(blank=True, max_length=100)),
                ('depIcon', models.ImageField(blank=True, upload_to='depIcon/')),
                ('depThumbnail', models.ImageField(blank=True, upload_to='depThumbnail/')),
                ('publish', models.BooleanField(default=True)),
                ('depMakeDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nestedapp.category')),
            ],
        ),
    ]
