# Generated by Django 4.1.2 on 2022-11-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nestedapp', '0005_alter_depertment_depicon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depertment',
            name='depIcon',
            field=models.ImageField(blank=True, upload_to='Icon/'),
        ),
        migrations.AlterField(
            model_name='depertment',
            name='depThumbnail',
            field=models.ImageField(blank=True, upload_to='Thumbnail/'),
        ),
    ]
