# Generated by Django 4.1.2 on 2022-11-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nestedapp', '0006_alter_depertment_depicon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depertment',
            name='depIcon',
        ),
        migrations.RemoveField(
            model_name='depertment',
            name='depThumbnail',
        ),
        migrations.AddField(
            model_name='depertment',
            name='dep_icon',
            field=models.ImageField(blank=True, upload_to='icon/'),
        ),
        migrations.AddField(
            model_name='depertment',
            name='dep_thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnail/'),
        ),
    ]
