# Generated by Django 4.1.2 on 2022-11-08 04:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nestedapp', '0007_remove_depertment_depicon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('startDate', models.DateField(default=datetime.datetime.now)),
                ('endDate', models.DateField()),
                ('icon', models.ImageField(blank=True, upload_to='iconSemester/')),
                ('publish', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nestedapp.category')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nestedapp.depertment')),
            ],
        ),
    ]
