# Generated by Django 4.1.2 on 2022-11-15 10:48

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('nestedapp', '0010_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('duratuion', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=500)),
                ('publish', models.BooleanField(default=True)),
                ('view', models.BooleanField(default=False)),
                ('stream', models.BooleanField(default=False)),
                ('thumnail', models.ImageField(blank=True, upload_to='vid_thumb/')),
                ('video', models.FileField(blank=True, upload_to='videos/')),
                ('creatDate', models.DateField(auto_now_add=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
