# Generated by Django 4.1.2 on 2022-11-16 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nestedapp', '0011_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='duratuion',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='thumnail',
            new_name='thumbnail',
        ),
    ]
