# Generated by Django 4.1.2 on 2023-01-05 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nestedapp', '0013_alter_video_duration_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='videoTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic', models.BooleanField(default=False)),
                ('premium', models.BooleanField(default=False)),
                ('diamond', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nestedapp.package')),
                ('videos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nestedapp.video')),
            ],
        ),
    ]
