# Generated by Django 4.1.2 on 2023-01-15 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nestedapp', '0014_videotopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_sub', to='nestedapp.category'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='nestedapp.depertment'),
        ),
        migrations.AlterField(
            model_name='videotopic',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='nestedapp.package'),
        ),
        migrations.AlterField(
            model_name='videotopic',
            name='videos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='nestedapp.video'),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, upload_to='instructor_pic/')),
                ('available', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='nestedapp.depertment')),
            ],
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('order', models.IntegerField(blank=True, max_length=50)),
                ('description', models.TextField(max_length=150)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('masenger', models.CharField(blank=True, max_length=100)),
                ('courseIcon', models.ImageField(blank=True, upload_to='courseIcon/')),
                ('courseBanner', models.ImageField(blank=True, upload_to='courseBanner/')),
                ('publish', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nestedapp.category')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nestedapp.depertment')),
                ('instructor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='nestedapp.instructor')),
                ('mentor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='nestedapp.instructor')),
                ('prerequisites', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nestedapp.coursemodel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nestedapp.subject')),
            ],
        ),
    ]
