# Generated by Django 4.1.2 on 2023-01-17 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nestedapp', '0018_alter_coursemodel_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='nestedapp.instructor'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='nestedapp.instructor'),
        ),
    ]
