# Generated by Django 4.1.2 on 2023-02-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nestedapp', '0021_sessionmodel_alter_coursemodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionmodel',
            name='year',
            field=models.IntegerField(max_length=50),
        ),
    ]
