# Generated by Django 4.1.2 on 2023-02-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nestedapp', '0022_alter_sessionmodel_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionmodel',
            name='year',
            field=models.CharField(max_length=50),
        ),
    ]
