# Generated by Django 4.1.2 on 2023-02-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nestedapp', '0025_sessioncategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='has_session',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='is_sub',
            field=models.BooleanField(default=False),
        ),
    ]
